import type { Metadata } from "next";
import { Fraunces, Geist, Geist_Mono, Kantumruy_Pro } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";

const kantumruy = Kantumruy_Pro({
  variable: "--font-kantumruy-pro--",
});

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${kantumruy.variable} ${fraunces.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Suspense fallback={<h1 className="bg-red-500 text-8xl">Loading....</h1>}>{children}</Suspense>
      </body>
    </html>
  );
}
